### ISSUE TITLE
npm init docusaurus => yarn create docusaurus

### ISSUE THREAD

**Issue by slorber** [nebrelbug/npm-to-yarn#21]
`npm init` should be converted to `yarn create`

We may create a `docusaurus-core` org or want to move this package in docusaurus main repo for better maintenance, would you transfer ownership?

Temporarily, I'd appreciate it if you could give me commit/publish access on GitHub/npm so that I can more easily fix things

Not having access creates some friction for me. For example this PR got blocked because of npm2yarn doc issue: https://github.com/facebook/docusaurus/pull/5635

**Comment by slorber** [comment]
Hi @nebrelbug , please let me know what your decision is so that I know what to do with the PR above

**Comment by slorber** [comment]
Hi @nebrelbug 

In case I don't get any news, I'm likely to fork this package and use the fork for Docusaurus.

Let me know if you can give me access

**Comment by Josh-Cena** [comment]
From their status / profile, seems they won't be available for at least another year. Docusaurus can use its own fork.
