### ISSUE TITLE
Allow ESM

### ISSUE THREAD

**Issue by Zamiell** [nebrelbug/npm-to-yarn#33]
Hello,

It appears that this package cannot be consumed by ESM projects. This is a shame, because it is relatively painless to publish libraries as dual CJS+ESM, so that they can be used by everybody. This blog goes into more detail:
https://antfu.me/posts/publish-esm-and-cjs

I propose that this package supports consumers who are using ESM.

**Comment by bgub** [comment]
@Zamiell hmm, I thought that the package was working fine with ESM. Where are you running into problems?

**Comment by Zamiell** [comment]
https://github.com/facebook/docusaurus/blob/main/packages/docusaurus-remark-plugin-npm2yarn/src/index.ts#L9-L10

**Comment by bgub** [comment]
@Zamiell I think that's outdated. They are using an old version of the package.

**Comment by Zamiell** [comment]
- The latest version of this package appears to be 1.2.1, from [this page](https://github.com/nebrelbug/npm-to-yarn/releases).
- We can see that the version of the package that "docusaurus-remark-plugin-npm2yarn" uses is 1.2.1, from [this page](https://github.com/facebook/docusaurus/blob/main/packages/docusaurus-remark-plugin-npm2yarn/package.json#L20).

Thus, why do you think that they are using an old version of the package?

**Comment by nebrelbug** [comment]
@Zamiell you're right, they are using the current version of the package. But I think that the @ts-expect-error tag is there just because previous versions of `npm-to-yarn` didn't work with NodeNext module resolution.

**Comment by bgub** [comment]
@Zamiell you're right, they are using the current version of the package. I'll test out NodeNext resolution.

**Comment by Zamiell** [comment]
That's incorrect. If you clone the repo, install deps, and then remove the line, you will immediately get a compiler error.

**Comment by bgub** [comment]
You may have been looking at my old comment.

**Comment by bgub** [comment]
I just opened #35 to fix this issue. Any feedback? If not I'll merge it and release a new version today.

**Comment by Zamiell** [comment]
I'm not familiar enough with the intricates of ESM to double-check your work, but regardless thank you very much for the swift update!

**Comment by bgub** [comment]
@Zamiell you're welcome! I just released the fix and opened a PR in the Docusaurus repo. I'll mark this as closed for now, unless further problems arise. I've tested in the Docusaurus repo and locally, though, so I don't expect that.

Thanks for the feedback!
