### ISSUE TITLE
Support pnpm

### ISSUE THREAD

**Issue by Zamiell** [nebrelbug/npm-to-yarn#34]
Hello,

It would be great if this library could support `pnpm`! In other words, the signature for the export should be changed from:

```ts
export default function convert(str: string, to: 'npm' | 'yarn'): string;
```

To:

```ts
export default function convert(str: string, to: 'npm' | 'yarn' | 'pnpm'): string;
```

From what I can gather, the syntax of pnpm is mostly the same as that of yarn. So this should be pretty easy.

For example:

- `npm install foo --save` --> `yarn add foo`
- `npm install foo --save` --> `pnpm add foo`

It's the same.

And:

- `npm install foo -D` --> `yarn add foo -D`
- `npm install foo -D` --> `pnpm add foo -D`

It's also the same.

However, there are some differences. For example:

- `npm install foo --save-dev` --> `yarn add foo --dev`
- `npm install foo --save-dev` --> `pnpm add foo --save-dev`

I'm by no means an expert in pnpm, so I'm sure there are more differences.

**Comment by bgub** [comment]
@Zamiell thanks for the idea! Would you be interested in submitting a PR?

**Comment by Zamiell** [comment]
I dont think I have time right now, sorry, but I just wanted to raise the issue.

**Comment by bgub** [comment]
@Zamiell no problem! I don't quite have time right now either, but I'll mark this as a feature request.
