### ISSUE TITLE
pnpm conversion should remove extra `--` used to pass npm args

### ISSUE THREAD

**Issue by slorber** [nebrelbug/npm-to-yarn#44]
**Describe the bug**

Related issue: https://github.com/facebook/docusaurus/pull/9761

```bash npm2yarn
npm run swizzle @docusaurus/theme-classic Footer -- --typescript
```

This is a valid npm command, although afaik `--` isn't required by the newest npm versions, older ones still require it.

Unfortunately, the extra `--` is not supported by yarn and pnpm

The yarn conversion already removes the extra `--` but not the pnpm one:

![CleanShot 2024-02-09 at 23 50 47@2x](https://github.com/nebrelbug/npm-to-yarn/assets/749374/125caff4-2eea-4e2f-9826-7916b2ed3994)

![CleanShot 2024-02-09 at 23 51 10@2x](https://github.com/nebrelbug/npm-to-yarn/assets/749374/784a8c73-42ee-4eae-90e4-1d9ef03d6a52)

![CleanShot 2024-02-09 at 23 51 22@2x](https://github.com/nebrelbug/npm-to-yarn/assets/749374/ab4b296c-605f-4774-8589-789de42e602a)

**To Reproduce**

On any docusaurus v3.1.1 (latest version) site:

````md
```bash npm2yarn
npm run swizzle @docusaurus/theme-classic Footer -- --typescript
```
````

**Expected behavior**

Convert to:

```bash npm2yarn
pnpm run swizzle @docusaurus/theme-classic Footer --typescript
```

Instead of:

```bash npm2yarn
pnpm run swizzle @docusaurus/theme-classic Footer -- --typescript
```

**Package & Environment Details**

- Environment: macOS, Node 18, npm 10

**Comment by bgub** [comment]
Just fixed in `npm-to-yarn@2.2.0`.
