### ISSUE TITLE
Feature request: add `npx` conversions

### ISSUE THREAD

**Issue by Jay-Karia** [nebrelbug/npm-to-yarn#48]
**Is your feature request related to a problem? Please describe.**
To convert `npx` commands to `yarn`, `pnpm`, and `bun` equivalent.

**Additional Context.**
According to me the equivalents would be:
Yarn - `yarn dlx`
Pnpm - `pnpm dlx`
Bun - `bun x`

**Comment by bgub** [comment]
I'd be open to merge a PR supporting this!

**Comment by Jay-Karia** [comment]
@nebrelbug will send a pull shortly

**Comment by Jay-Karia** [comment]
Here's a solution I thought about:

We can add a new parameter to `convert` function, which will be `executor` of type `boolean` with a default value `false`.
This will return the desired command for `npx` equivalent.

**Comment by Jay-Karia** [comment]
@nebrelbug can you guide be about local development?

**Comment by Jay-Karia** [comment]
@nebrelbug ?

**Comment by slorber** [comment]
can be closed?
