### ISSUE TITLE
Broken Link in README

### ISSUE THREAD

**Issue by Jay-Karia** [nebrelbug/npm-to-yarn#50]
**Describe the bug**
There is an broken link in README file for "Dev Dependencies" Badge.

**To Reproduce**

1. Navigate to project's README file.
2. Visit the top section of the badges

**Expected behavior**
A broken link in the badge

**Screenshots**
![broken link](https://github.com/user-attachments/assets/d1fa40b0-a568-47c3-9fbd-2a9783894283)

**Additional context**
The link specified in readme: https://img.shields.io/david/dev/nebrelbug/npm-to-yarn, leads to "404 badge not found"

**Comment by bgub** [comment]
Thanks for noticing this!
