### ISSUE TITLE
`npm create` couldn't convert.

### ISSUE THREAD

**Issue by m1m0zzz** [nebrelbug/npm-to-yarn#62]
**Describe the bug**

When I try to convert `npm create`, which is an alias of `npm init`, I get `# couldn't auto-convert command`

**To Reproduce**

1. Type in 'npm create'

**Expected behavior**
\- 

**Screenshots**

![image](https://github.com/user-attachments/assets/73972530-c387-4132-a7c6-622e3c37a0ac)

**Package & Environment Details**

- Test page (probably the latest version) (3.0.0)
- (docusaurus 3.6.3)

**Additional context**
\-

**Comment by bgub** [comment]
Closed by #63 and released in 3.0.1!
