### ISSUE TITLE
Remove useless -- in "npm run myScript -- --arg"

### ISSUE THREAD

**Issue by slorber** [nebrelbug/npm-to-yarn#8]
**Is your feature request related to a problem? Please describe.**

Convert a command running with extra args (using the `--` npm syntax) as a good Yarn equivalent (not using `--`).

`yarn run crowdin -- --version`

> warning From Yarn 1.0 onwards, scripts don't require "--" for options to be forwarded. In a future version, any explicit "--" will be forwarded as-is to the scripts.

**Describe the solution you'd like**

`npm run myScript -- --version` => `yarn myScript --version` (related to https://github.com/nebrelbug/npm-to-yarn/issues/7)

**Describe alternatives you've considered**

None

**Additional context**

Want to improve the Yarn experience on Docusaurus, like on this page:

https://deploy-preview-4014--docusaurus-2.netlify.app/classic/docs/next/i18n/introduction

**Comment by Zamiell** [comment]
Should this be closed now?

**Comment by bgub** [comment]
@Zamiell yes, thank you.
