### ISSUE TITLE
Publish web client

### ISSUE THREAD

**Issue by varunsingh87** [nebrelbug/npm-to-yarn#9]
**Is your feature request related to a problem? Please describe.**
Even though this is a lightweight package, I don't want to have to open a new Node project in order to convert the commands, copy from the console, and paste wherever I need to. Writing a Node script may not even be possible for everyone at all times to do.

**Describe the solution you'd like**
To solve this problem, I think we should have a simple web client - only pure HTML, CSS, and JavaScript is needed - with an `<input>` field, an `<output>` tag, and minimal JavaScript for actually doing the conversion. 

**Describe alternatives you've considered**
You can instead have a link to an online JavaScript environment with this package already loaded, and people can fork that to write the script. 

**Additional context**
I am looking to contribute to open-source, and, as I do know HTML, CSS, JavaScript, and Node, I can take up this feature and build it. 

An interface as like this, both clean and simple, is what I'm thinking:
![RawGit to jsDelivr converter with clean interface](https://user-images.githubusercontent.com/31084854/113495028-5ffb4f80-94bc-11eb-87cf-6fe3678a9385.png)
https://www.jsdelivr.com/rawgit

**Comment by varunsingh87** [comment]
**EDIT**

I have just realized that a test.html already exists. In that case, can you serve up this package on GitHub Pages so there's a public link to it?

**Comment by bgub** [comment]
Thanks for the suggestion! Yep, I just enabled GitHub pages. The link is https://nebrelbug.github.io/npm-to-yarn/test.html

**Comment by bgub** [comment]
@varunsingh87 and thanks for the offer to contribute! If you find anything else you'd like to contribute to, feel free to create a PR!

**Comment by varunsingh87** [comment]
Thanks for getting back to me! I'd be happy to continue contributing.
